#!/bin/sh

cek=$(curl -s http://worldtimeapi.org/api/timezone/Asia/Jakarta.txt|grep -w "datetime"|sed 's/^.*: //')
tanggal="${cek:0:10}"
jam="${cek:11:8}"

sed -i '/exit 0/d' /etc/rc.local
sed -i '/date -s/d' /etc/rc.local
echo -e "\ndate -s \"${tanggal} ${jam}\"\nexit 0" >> /etc/rc.local
