#!/bin/bash

cek=$(curl -f -s http://worldtimeapi.org/api/timezone/Asia/Jakarta.txt|grep -w "datetime"|sed 's/^.*: //')
tanggal="${cek:0:10}"
jam="${cek:11:8}"

if [ -z "$tanggal" -o -z "$jam" ]; then
	logger -t sync-time "Gagal mendapatkan waktu terbaru"
	exit 1
fi

#cmd

logger -t sync-time "Sukses memperbarui tanggal"
