#!/bin/sh

if [[ $1 = "install" ]]; then
	curl -f -s -o /etc/cek_waktu https://raw.githubusercontent.com/utoro/openwrt-sync-time/main/cek_waktu && chmod +x /etc/cek_waktu || { echo 'Install gagal! Periksa koneksi internet' ; exit 1; }
	
	sed -i '/cek_waktu/d' /etc/crontabs/root
	echo -e "\n0 * * * * /etc/cek_waktu >/dev/null 2>&1" >> /etc/crontabs/root
	/etc/init.d/cron restart

	. /etc/cek_waktu
	echo -e "Install script sukses!"
	exit 0
elif [[ $1 = "uninstall" ]]; then
	sed -i '/cek_waktu/d' /etc/crontabs/root
	/etc/init.d/cron restart
	sed -i '/date -s/d' /etc/rc.local
	rm -f /etc/cek_waktu
	echo -e "Uninstall script sukses!"
	exit 0
else
	echo "Gagal! Perintah tidak dikenal"
	exit 1
fi
