#!/bin/bash

if [[ $1 = "install" ]]; then
	
	curl -f -s -o /usr/bin/set-waktu https://raw.githubusercontent.com/utoro/openwrt-sync-time/new_feature/set-waktu && chmod +x /usr/bin/set-waktu || { echo 'Install script gagal! Periksa koneksi internet' ; exit 1; }
	
	if [[ $2 = "startup" ]]; then
		cmd="#!/bin/sh /etc/rc.common\nSTART=13\n\nstart () {\n\tlogger -t fix-time \"Proses fix-time dijalankan\"\n\twaktu=\"$tanggal $jam\"\n\tdate -s \"\$waktu\"\n\tlogger -t fix-time \"Berhasil set waktu ke \$waktu\"\n}"
		echo -e $cmd > /etc/init.d/fix-time && chmod +x /etc/init.d/fix-time && /etc/init.d/fix-time enable

		cmd="sed -i \"s\|.*waktu=.*\|\\\twaktu=$(echo "\\\\")\"\$tanggal \$jam$(echo "\\\\")\"\|\" /etc/init.d/fix-time"
		sed -i "s|#cmd|$cmd|g" /usr/bin/set-waktu
	elif [[ $2 = "rc.local" ]]; then
		cmd="sed -i '/exit 0/d' /etc/rc.local\nsed -i '/date -s/d' /etc/rc.local\nsed -i '/# fix reset 2015/d' /etc/rc.local\nsed -i '\$a# fix reset 2015' /etc/rc.local\necho -e \"date -s $(echo "\\\\")\"\${tanggal} \${jam}$(echo "\\\\")\"\\\nexit 0\" >> /etc/rc.local"
		sed -i "s|#cmd|$cmd|g" /usr/bin/set-waktu
	else
		echo "Gagal! Perintah tidak dikenal"
		echo "contoh: $0 $1 <startup | rc.local>"
		exit 1
	fi

	(. /usr/bin/set-waktu) || { echo "Install script gagal! Periksa koneksi internet"; exit 1; }

	sed -i '/set-waktu/d' /etc/crontabs/root
	sed -i '/# fix reset 2015/d' /etc/crontabs/root
	sed -i '$a# fix reset 2015' /etc/crontabs/root
	echo -e "0 * * * * /usr/bin/set-waktu >/dev/null 2>&1" >> /etc/crontabs/root
	/etc/init.d/cron restart

	echo -e "Install script sukses!"
	exit 0
elif [[ $1 = "uninstall" ]]; then
	if [ -f /etc/init.d/fix-time ]; then
		/etc/init.d/fix-time stop
		/etc/init.d/fix-time disable
		rm -f /etc/init.d/fix-time
		echo "File fix-time berhasil dihapus"
	fi

	sed -i '/set-waktu/d' /etc/crontabs/root
	sed -i '/# fix reset 2015/d' /etc/crontabs/root
	/etc/init.d/cron restart
	sed -i '/date -s/d' /etc/rc.local
	sed -i '/# fix reset 2015/d' /etc/rc.local
	rm -f /usr/bin/set-waktu
	echo -e "Uninstall script sukses!"
	exit 0
else
	echo "Gagal! Perintah tidak dikenal"
	echo "contoh: $0 <install | uninstall>"
	exit 1
fi
